services:
  selenium:
    container_name: ${CONTAINER_PREFIX:-scraping}-selenium
    image: selenium/standalone-chrome:4.1.4-20220427
    ports:
      - 4444:4444
      - 7900:7900
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/wd/hub/status" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  mysql:
    container_name: ${CONTAINER_PREFIX:-scraping}-db
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT:-3306}:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

  minio:
    container_name: ${CONTAINER_PREFIX:-scraping}-minio
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s

  app:
    container_name: ${CONTAINER_PREFIX:-scraping}-app
    build: .
    depends_on:
      selenium:
        condition: service_healthy
      mysql:
        condition: service_started
      minio:
        condition: service_healthy
    volumes:
      - ./src:/src
      - ./setup.py:/setup.py
      - ./credentials.json:/src/credentials.json
    env_file:
      - .env
    networks:
      - app-network
    tty: true
    stdin_open: true

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  minio_data:
